location:
  latitude: null
  longitude: null
  timezone: null

weather:
  current:
    - temperature_2m
    - relative_humidity_2m
    - apparent_temperature
    - is_day
    - precipitation
    - rain
    - showers
    - snowfall
    - weather_code
    - cloud_cover
    - wind_speed_10m
    - wind_direction_10m
    - wind_gusts_10m

  hourly:
    - temperature_2m
    - precipitation_probability
    - precipitation
    - rain
    - showers
    - snowfall
    - snow_depth
    - cloud_cover
    - cloud_cover_low
    - cloud_cover_mid
    - cloud_cover_high
    - visibility
    - wind_speed_10m
    - wind_direction_10m
    - wind_gusts_10m
    - surface_temperature

  daily:
    - temperature_2m_max
    - temperature_2m_min
    - sunrise
    - sunset
    - rain_sum
    - showers_sum
    - snowfall_sum
    - precipitation_hours
    - precipitation_probability_max
    - wind_speed_10m_max
    - wind_gusts_10m_max
    - wind_direction_10m_dominant

units:
  temperature: fahrenheit
  wind_speed: mph
  precipitation: inch
  models: gfs_seamless
